### ISSUE TITLE
Could not find artifact in maven central repository

### ISSUE THREAD

**Issue by tremkonzah** [mdolinin/maven-thucydides-jbehave-plugin#31]
I try to add this in maven pom.xml file and getting below error:

Could not find artifact net.thucydides.maven.plugin:maven-thucydides-jbehave-plugin:jar:0.9.223 in central (https://repo.maven.apache.org/maven2)

**Comment by mdolinin** [comment]
First this jar was never published in maven central. If you want to use it, you need to build it from sources or download and put it in your repository directly.
Second i am not sure that it will work with Serenity. It was developed forThucydides. And i have no plans to migrate to Serenity.

**Comment by tremkonzah** [comment]
Yeah it does not work with Serenity. Hopefully you'll have sometimes to migrate it to Serenity :)
